### ISSUE TITLE
results on the MedDG dataset

### ISSUE THREAD

**Issue by qkty-0104** [FlyingCat-fa/TSPMN#2]
Could you tell me how to get results on the MedDG dataset in the paper? The provided 'evaluate.py' seems to only work with the processed MSL dataset.

**Comment by FlyingCat-fa** [comment]
Sorry. We have upload the processed MedDG dataset. You can train the MedDG and evaluate it. Just modify the dir from MSL to MedDG.

**Comment by qkty-0104** [comment]
Thanks so much for the valuable resources you provided.
